const ADD_QUESTION = 'ADD_QUESTION';
const SET_SELECTED_QUESTION = 'SET_SELECTED_QUESTION';
const UPDATE_ANSWER_VALUE = 'UPDATE_ANSWER_VALUE';
const FETCH_QUESTIONS_TOP = 'FETCH_QUESTIONS_TOP';
const UPDATE_LOADING = 'UPDATE_LOADING';
export { ADD_QUESTION, FETCH_QUESTIONS_TOP, SET_SELECTED_QUESTION, UPDATE_ANSWER_VALUE, UPDATE_LOADING };
